/**
 * @file minic.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE minic.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _MINIC_H_
#define _MINIC_H_

#include "snetentities.h"

#define E__minic__NONE 0
#define F__minic__A 1
#define F__minic__X 2

#define SNET__minic__NUMBER_OF_LABELS 3


#define I__minic__C4SNet 0

#define SNET__minic__NUMBER_OF_INTERFACES 1


extern char *snet_minic_labels[];

extern char *snet_minic_interfaces[];


extern snet_tl_stream_t *SNet__minic___minic(snet_tl_stream_t *in_buf);

#endif

