/**
 * @file des.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE des.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _DES_H_
#define _DES_H_

#include "snetentities.h"

#define F__des__Op1	1
#define F__des__Op2	2
#define F__des__Result	3
#define F__des__Pt	4
#define F__des__L	5
#define F__des__R	6
#define F__des__Key	7
#define F__des__KeySet	8
#define F__des__Ct	9
#define F__des__Rx	10
#define F__des__NextKey	11
#define F__des__BitStr	12
#define F__des__SStr	13
#define F__des__Rf	14
#define F__des__Rn	15
#define T__des__C	16

extern snet_buffer_t *SNet__des___des(snet_buffer_t *in_buf);

#endif

