/**
 * @file des.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE des.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "des.h"
#include "xor.h"
#include "InitialP.h"
#include "genSubKeys.h"
#include "FinalP.h"
#include "BitExpand.h"
#include "SubKey.h"
#include "Substitute.h"
#include "Pbox.h"

static void SNet__des__xor(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_Op1 = NULL;
  void *field_Op2 = NULL;

  rec = SNetHndGetRecord(hnd);

  field_Op1 = SNetRecTakeField(rec, F__des__Op1);

  field_Op2 = SNetRecTakeField(rec, F__des__Op2);
  //printf("->xor\n");
  xor(hnd, field_Op1, field_Op2);
  //printf("xor->\n");

}

static void SNet__des__InitialP(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_Pt = NULL;

  rec = SNetHndGetRecord(hnd);

  field_Pt = SNetRecTakeField(rec, F__des__Pt);
  //printf("->InitialP\n");

  InitialP(hnd, field_Pt);
  //printf("InitialP->\n");
}

static void SNet__des__genSubKeys(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_Key = NULL;

  rec = SNetHndGetRecord(hnd);

  field_Key = SNetRecTakeField(rec, F__des__Key);
  //printf("->genSubKeys\n");
  genSubKeys(hnd, field_Key);
  //printf("genSubKeys->\n");
}

static void SNet__des__FinalP(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_L = NULL;
  void *field_R = NULL;

  rec = SNetHndGetRecord(hnd);

  field_L = SNetRecTakeField(rec, F__des__L);

  field_R = SNetRecTakeField(rec, F__des__R);
  //printf("->FinalP\n");

  FinalP(hnd, field_L, field_R);
  //printf("FinalP->\n");
}

static void SNet__des__desRound__feistel__ExpandAndKeySelect__BitExpand(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_R = NULL;

  rec = SNetHndGetRecord(hnd);
  //printf("->BitExpand\n");
  field_R = SNetRecTakeField(rec, F__des__R);

  BitExpand(hnd, field_R);
  //printf("BitExpand->\n");
}

static void SNet__des__desRound__feistel__ExpandAndKeySelect__SubKey(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_KeySet = NULL;
  int stag_C = 0;

  rec = SNetHndGetRecord(hnd);

  field_KeySet = SNetRecTakeField(rec, F__des__KeySet);

  stag_C = SNetRecTakeTag(rec, T__des__C);
  //printf("->SubKey\n");
  SubKey(hnd, field_KeySet, stag_C);
  //printf("SubKey->\n");
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__R, F__des__KeySet), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(2, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__R, F__des__R)), 
                SNetCreateFilterInstructionSet(3, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__KeySet, F__des__KeySet), 
                  SNetCreateFilterInstruction(snet_tag, T__des__C, 
                    SNetEtag( T__des__C)))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL___PL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Rx),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));
  out_buf = SNetBox(in_buf, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect__BitExpand, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL___PR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 2, F__des__KeySet, F__des__NextKey),
        SNetTencCreateVector( 1, T__des__C),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect__SubKey, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, 
    SNetTencTypeEncode( 2,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__R),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)),
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__KeySet),
        SNetTencCreateVector( 1, T__des__C),
        SNetTencCreateVector( 0))),
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL___PL, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL___PR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SR___ST(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSync(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__NextKey, F__des__Rx), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              SNetTencTypeEncode(2, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__NextKey), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0)), 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__Rx), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL);

  return (out_buf);
}

static snet_buffer_t *SNet____STAR_INCARNATE_des__desRound__feistel__ExpandAndKeySelect___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__NextKey, F__des__Rx), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SR___ST, 
              &SNet____STAR_INCARNATE_des__desRound__feistel__ExpandAndKeySelect___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__NextKey, F__des__Rx), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SR___ST, 
              &SNet____STAR_INCARNATE_des__desRound__feistel__ExpandAndKeySelect___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SL, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__ExpandAndKeySelect(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SL, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__KeyMix___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__NextKey, F__des__Rx), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(3, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__Op1, F__des__NextKey), 
                  SNetCreateFilterInstruction(snet_field, F__des__Op2, F__des__Rx))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__KeyMix___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
     SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Result),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0))); 

  out_buf = SNetBox(in_buf, 
              &SNet__des__xor, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__KeyMix___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__Result), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__BitStr, F__des__Result))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__KeyMix___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__KeyMix___SR___SL, 
              &SNet__des__desRound__feistel__KeyMix___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel__KeyMix(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__KeyMix___SL, 
              &SNet__des__desRound__feistel__KeyMix___SR);

  return (out_buf);
}

static void SNet__des__desRound__feistel__Substitute(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_BitStr = NULL;

  rec = SNetHndGetRecord(hnd);

  field_BitStr = SNetRecTakeField(rec, F__des__BitStr);

  //printf("->Substitute\n");
  Substitute(hnd, field_BitStr);
  //printf("Substitute->\n");
}

static void SNet__des__desRound__feistel__Pbox(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_SStr = NULL;

  rec = SNetHndGetRecord(hnd);

  field_SStr = SNetRecTakeField(rec, F__des__SStr);

  //printf("->Pbox\n");
  Pbox(hnd, field_SStr);
  //printf("Pbox->\n");
}

static snet_buffer_t *SNet__des__desRound__feistel___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__SStr),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__desRound__feistel__Substitute, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel___SR___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Rf),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__desRound__feistel__Pbox, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel___SR___SR___SL, 
              &SNet__des__desRound__feistel___SR___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__KeyMix, 
              &SNet__des__desRound__feistel___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__feistel(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__feistel__ExpandAndKeySelect, 
              &SNet__des__desRound__feistel___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__XorHalfBlocks___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__Rf), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(3, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__Op1, F__des__L), 
                  SNetCreateFilterInstruction(snet_field, F__des__Op2, F__des__Rf))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__XorHalfBlocks___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Result),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__xor, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__XorHalfBlocks___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__Result), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__R, F__des__Result))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__XorHalfBlocks___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__XorHalfBlocks___SR___SL, 
              &SNet__des__desRound__XorHalfBlocks___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound__XorHalfBlocks(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound__XorHalfBlocks___SL, 
              &SNet__des__desRound__XorHalfBlocks___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(3, F__des__L, F__des__R, F__des__KeySet), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(2, 
                SNetCreateFilterInstructionSet(5, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__L, F__des__L), 
                  SNetCreateFilterInstruction(snet_field, F__des__R, F__des__R), 
                  SNetCreateFilterInstruction(snet_field, F__des__KeySet, F__des__KeySet), 
                  SNetCreateFilterInstruction(snet_tag, T__des__C, 
                    SNetEadd( 
                      SNetEtag( T__des__C), 
                      SNetEconsti( 1)))), 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__Rn, F__des__R))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__Rn), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__L, F__des__Rn))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(3, F__des__L, F__des__R, F__des__KeySet), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(2, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__L, F__des__L)), 
                SNetCreateFilterInstructionSet(4, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__R, F__des__R), 
                  SNetCreateFilterInstruction(snet_field, F__des__KeySet, F__des__KeySet), 
                  SNetCreateFilterInstruction(snet_tag, T__des__C, 
                    SNetEtag( T__des__C)))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR___SL___PL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__L), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(2, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__L, F__des__L))));

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, 
    SNetTencTypeEncode( 2,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__L),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)),
      SNetTencVariantEncode(
        SNetTencCreateVector( 2, F__des__KeySet, F__des__R),
        SNetTencCreateVector( 1, T__des__C),
        SNetTencCreateVector( 0))),
              &SNet__des__desRound___SR___SL___PR___SR___SL___PL, 
              &SNet__des__desRound__feistel);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR___SR___SL___ST(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSync(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__Rf), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              SNetTencTypeEncode(2, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__L), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0)), 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__Rf), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL);

  return (out_buf);
}

static snet_buffer_t *SNet____STAR_INCARNATE_des__desRound___SR___SL___PR___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__Rf), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound___SR___SL___PR___SR___SR___SL___ST, 
              &SNet____STAR_INCARNATE_des__desRound___SR___SL___PR___SR___SR___SL);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__Rf), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound___SR___SL___PR___SR___SR___SL___ST, 
              &SNet____STAR_INCARNATE_des__desRound___SR___SL___PR___SR___SR___SL);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound___SR___SL___PR___SR___SR___SL, 
              &SNet__des__desRound__XorHalfBlocks);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound___SR___SL___PR___SR___SL, 
              &SNet__des__desRound___SR___SL___PR___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL___PR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound___SR___SL___PR___SL, 
              &SNet__des__desRound___SR___SL___PR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, 
    SNetTencTypeEncode( 2,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Rn),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)),
      SNetTencVariantEncode(
        SNetTencCreateVector( 2, F__des__KeySet, F__des__L, F__des__R),
        SNetTencCreateVector( 1, T__des__C),
        SNetTencCreateVector( 0))),
              &SNet__des__desRound___SR___SL___PL, 
              &SNet__des__desRound___SR___SL___PR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SR___ST(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSync(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__R), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              SNetTencTypeEncode(2, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__L), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0)), 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__R), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL);

  return (out_buf);
}

static snet_buffer_t *SNet____STAR_INCARNATE_des__desRound___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__R), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound___SR___SR___ST, 
              &SNet____STAR_INCARNATE_des__desRound___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(2, F__des__L, F__des__R), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              &SNet__des__desRound___SR___SR___ST, 
              &SNet____STAR_INCARNATE_des__desRound___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound___SR___SL, 
              &SNet__des__desRound___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des__desRound(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des__desRound___SL, 
              &SNet__des__desRound___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 2, F__des__R, F__des__L),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__InitialP, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__KeySet),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__genSubKeys, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(3, F__des__L, F__des__R, F__des__KeySet), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(5, 
                  SNetCreateFilterInstruction(create_record), 
                  SNetCreateFilterInstruction(snet_field, F__des__L, F__des__L), 
                  SNetCreateFilterInstruction(snet_field, F__des__R, F__des__R), 
                  SNetCreateFilterInstruction(snet_field, F__des__KeySet, F__des__KeySet), 
                  SNetCreateFilterInstruction(snet_tag, T__des__C, 
                    SNetEsub( 
                      SNetEconsti( 0), 
                      SNetEconsti( 1))))));

  return (out_buf);
}

static snet_buffer_t *SNet____STAR_INCARNATE_des___SR___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              SNetEcreateList(1, 
                SNetEeq( 
                  SNetEtag( T__des__C), 
                  SNetEconsti( 3))), 
              &SNet__des__desRound, 
              &SNet____STAR_INCARNATE_des___SR___SR___SR___SL);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              SNetEcreateList(1, 
                SNetEeq( 
                  SNetEtag( T__des__C), 
                  SNetEconsti( 3))), 
              &SNet__des__desRound, 
              &SNet____STAR_INCARNATE_des___SR___SR___SR___SL);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SR___SR___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = 
    SNetTencTypeEncode( 1,
      SNetTencVariantEncode(
        SNetTencCreateVector( 1, F__des__Ct),
        SNetTencCreateVector( 0),
        SNetTencCreateVector( 0)));

  out_buf = SNetBox(in_buf, 
              &SNet__des__FinalP, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SR___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(1, F__des__KeySet), 
                  SNetTencCreateVector(1, T__des__C), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(1, 
                  SNetCreateFilterInstruction(create_record))));

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des___SR___SR___SR___SR___SL, 
              &SNet__des___SR___SR___SR___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des___SR___SR___SR___SL, 
              &SNet__des___SR___SR___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des___SR___SR___SL, 
              &SNet__des___SR___SR___SR);

  return (out_buf);
}

static snet_buffer_t *SNet__des___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des___SR___SL, 
              &SNet__des___SR___SR);

  return (out_buf);
}

snet_buffer_t *SNet__des___des(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__des___SL, 
              &SNet__des___SR);

  return (out_buf);
}

