typedef enum proc_state proc_state_t;
typedef enum res_kind res_kind_t;
typedef enum token token_t;
typedef int intlist_iter_t;
typedef int intmap_iter_t;
typedef struct cache cache_t;
typedef struct core core_t;
typedef struct host host_t;
typedef struct intlist intlist_t;
typedef struct intmap intmap_t;
typedef struct numa numa_t;
typedef struct proc proc_t;
typedef struct resource resource_t;
