/**
 * @file minic.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE minic.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "minic.h"
#include "networkinterface.h"
#include "observers.h"
#include "C4SNet.h"

char *snet_minic_labels[] = {
	"E__minic__None",
	"A"};

char *snet_minic_interfaces[] = {
	"C4SNet"};

extern void *init( void *hnd);

void *SNetCall__init( void *handle)
{
  return( init( handle));
}

static void SNet__minic__init(snet_handle_t *hnd)
{
  snet_record_t *rec = NULL;

  rec = SNetHndGetRecord(hnd);

  SNetCall__init(hnd);
}

extern void *dec( void *hnd, void *arg_0);

void *SNetCall__dec( void *handle, void *arg_0)
{
  return( dec( handle, arg_0));
}

static void SNet__minic__dec(snet_handle_t *hnd)
{
  snet_record_t *rec = NULL;
  void *field_A = NULL;

  rec = SNetHndGetRecord(hnd);

  field_A = SNetRecTakeField(rec, F__minic__A);

  SNetCall__dec(hnd, field_A);
}

static snet_tl_stream_t *SNet__minic___SL___P1(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;
  snet_box_sign_t *out_sign = NULL;

  out_type = SNetTencTypeEncode(1, 
              SNetTencVariantEncode(
                SNetTencCreateVector(1, F__minic__A), 
                SNetTencCreateVector(0), 
                SNetTencCreateVector(0)));


  out_sign = SNetTencBoxSignEncode( out_type, 
              SNetTencCreateVector(1, field));


  out_buf = SNetBox(in_buf, "init", 
              &SNet__minic__init, 
              out_sign);

  return (out_buf);
}

static snet_tl_stream_t *SNet__minic___SL___P2(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, 
              SNetTencTypeEncode(1, 
                SNetTencVariantEncode(
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0), 
                  SNetTencCreateVector(0))), 
              NULL, 
              SNetCreateFilterInstructionSetList(1, 
                SNetCreateFilterInstructionSet(1, 
                  SNetCreateFilterInstruction(create_record))));

  return (out_buf);
}

static snet_tl_stream_t *SNet__minic___SL(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, 
              SNetTencCreateTypeEncodingList(2, 
                SNetTencTypeEncode(0), 
                SNetTencTypeEncode(1, 
                  SNetTencVariantEncode(
                    SNetTencCreateVector(0), 
                    SNetTencCreateVector(0), 
                    SNetTencCreateVector(0)))), 
              &SNet__minic___SL___P1, 
              &SNet__minic___SL___P2);

  return (out_buf);
}

static snet_tl_stream_t *SNet____OBSERVED__minic___SR(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;
  snet_box_sign_t *out_sign = NULL;

  out_type = SNetTencTypeEncode(1, 
              SNetTencVariantEncode(
                SNetTencCreateVector(1, F__minic__A), 
                SNetTencCreateVector(0), 
                SNetTencCreateVector(0)));


  out_sign = SNetTencBoxSignEncode( out_type, 
              SNetTencCreateVector(1, field));


  out_buf = SNetBox(in_buf, "dec", 
              &SNet__minic__dec, 
              out_sign);

  return (out_buf);
}

static snet_tl_stream_t *SNet____OBSERVER__BEFORE__minic___SR(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetObserverSocketBox(in_buf, 
              "localhost", 
              6555, 
              true, 
              "dec", 
              SNET_OBSERVERS_TYPE_BEFORE, 
              SNET_OBSERVERS_DATA_LEVEL_LABELS, 
              NULL);

  return (out_buf);
}

static snet_tl_stream_t *SNet____OBSERVER__AFTER__minic___SR(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetObserverSocketBox(in_buf, 
              "localhost", 
              6555, 
              true, 
              "dec", 
              SNET_OBSERVERS_TYPE_AFTER, 
              SNET_OBSERVERS_DATA_LEVEL_LABELS, 
              NULL);

  return (out_buf);
}

static snet_tl_stream_t *SNet____OBSERVER__AUX__minic___SR(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet____OBSERVER__BEFORE__minic___SR, 
              &SNet____OBSERVED__minic___SR);

  return (out_buf);
}

static snet_tl_stream_t *SNet__minic___SR(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet____OBSERVER__AUX__minic___SR, 
              &SNet____OBSERVER__AFTER__minic___SR);

  return (out_buf);
}

snet_tl_stream_t *SNet__minic___minic(snet_tl_stream_t *in_buf)
{
  snet_tl_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__minic___SL, 
              &SNet__minic___SR);

  return (out_buf);
}

int SNetMain__minic(int argc, char* argv[])
{
  int ret = 0;

  SNetGlobalInitialise();

  C4SNetInit(I__minic__C4SNet);
  
  ret = SNetInRun(argc, argv,
              snet_minic_labels,
              SNET__minic__NUMBER_OF_LABELS,
              snet_minic_interfaces,
              SNET__minic__NUMBER_OF_INTERFACES,
              SNet__minic___minic);

  SNetGlobalDestroy();

  return( ret);
}

