/**
 * @file test.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE test.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TEST_H_
#define _TEST_H_

#include "snetentities.h"

#define E__test__NONE 0
#define F__test__a 1
#define F__test__b 2
#define F__test__c 3
#define F__test__d 4
#define F__test__e 5
#define F__test__f 6
#define T__test__T 7

#define SNET__test__NUMBER_OF_LABELS 8



#define SNET__test__NUMBER_OF_INTERFACES 0


extern char *snet_test_labels[];

extern char *snet_test_interfaces[];


extern snet_tl_stream_t *SNet__test___test(snet_tl_stream_t *in_buf);

#endif

