/**
 * @file factorial.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE factorial.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "factorial.h"
#include "leq1.h"
#include "condif.h"

static void SNet__factorial__leq1(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_x = NULL;

  rec = SNetHndGetRecord(hnd);

  field_x = SNetRecTakeField(rec, F__factorial__x);

  leq1(hnd, field_x);
}

static void SNet__factorial__condif(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_p = NULL;

  rec = SNetHndGetRecord(hnd);

  field_p = SNetRecTakeField(rec, F__factorial__p);

  condif(hnd, field_p);
}

static snet_buffer_t *SNet__factorial___SL(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;

  out_type = SNetTencTypeEncode(1, 
              SNetTencVariantEncode(
                SNetTencCreateVector(2, F__factorial__x, F__factorial__p), 
                SNetTencCreateVector(0), 
                SNetTencCreateVector(0)));

  out_buf = SNetBox(in_buf, 
              &SNet__factorial__leq1, 
              out_type);

  return (out_buf);
}

static snet_buffer_t *SNet__factorial___SR(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;

  out_type = SNetTencTypeEncode(2, 
              SNetTencVariantEncode(
                SNetTencCreateVector(0), 
                SNetTencCreateVector(1, T__factorial__T), 
                SNetTencCreateVector(0)), 
              SNetTencVariantEncode(
                SNetTencCreateVector(0), 
                SNetTencCreateVector(1, T__factorial__F), 
                SNetTencCreateVector(0)));

  out_buf = SNetBox(in_buf, 
              &SNet__factorial__condif, 
              out_type);

  return (out_buf);
}

snet_buffer_t *SNet__factorial___factorial(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, 
              &SNet__factorial___SL, 
              &SNet__factorial___SR);
	    
  return (out_buf);
}

