/**
 * @file factorial.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE factorial.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _FACTORIAL_H_
#define _FACTORIAL_H_

#include "snetentities.h"

#define F__factorial__x	1
#define F__factorial__p	2
#define F__factorial__xx	3
#define F__factorial__r	4
#define F__factorial__rr	5
#define T__factorial__T	6
#define T__factorial__F	7
#define T__factorial__stop	8

extern snet_buffer_t *SNet__factorial___factorial(snet_buffer_t *in_buf);

#endif

