/**
 * @file factorial.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE factorial.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _FACTORIAL_H_
#define _FACTORIAL_H_

#include "snetentities.h"

#define E__factorial__NONE 0
#define F__factorial__x 1
#define F__factorial__p 2
#define T__factorial__T 3
#define T__factorial__F 4

#define SNET__factorial__NUMBER_OF_LABELS 5

char *snet_factorial_labels[] = {
	"E__factorial__None",
	"F__factorial__x",
	"F__factorial__p",
	"T__factorial__T",
	"T__factorial__F"};

extern snet_buffer_t *SNet__factorial___factorial(snet_buffer_t *in_buf);

#endif

