#ifndef _SNET_SNETTYPES_H_
#define _SNET_SNETTYPES_H_

#include "typeencode.h"
#include "expression.h"
#include "filter.h"
#include "handle.h"
#include "record.h"



/* runtime specific implementation */
struct stream;
typedef struct stream snet_stream_t;




/* Type for start-up functions generated by snet compiler: */
#ifdef DISTRIBUTED_SNET
#include "info.h"
typedef snet_stream_t *(*snet_startup_fun_t)(snet_stream_t *, snet_info_t *, int);
#else
typedef snet_stream_t *(*snet_startup_fun_t)(snet_stream_t *);
#endif

/* Type for box function */
typedef void (*snet_box_fun_t)(snet_handle_t *);
//typedef void (*snet_box_fun_t)(struct handle *);

#endif /* _SNET_SNETTYPES_H_ */
