/*
 * C interface header file for modules:
 *
 *   boxes
 *
 * generated by sac4c v1.00-beta (Haggis And Apple) (developer) rev 16788
 */

#include "sacinterface.h"


#define SACTYPE_Color8_color 20
#define SACTYPE_ComplexBasics_complex 21
#define SACTYPE_Complex_complex 21
#define SACTYPE_Structures_complex 21
#define SACTYPE_SNet_SNet 24
#define SACTYPE_Structures_color 20

/*****************************************************************************
 * C declaration of function boxes::doubleArrayToRGB.
 *
 * defined instances:
 *
 * ( double[.,.]) -> ( Color8::color[.,.])
 *
 *****************************************************************************/

extern void boxes__doubleArrayToRGB1(SACarg **ret1, SACarg *arg1);

/*****************************************************************************
 * C declaration of function boxes::escapeValue.
 *
 * defined instances:
 *
 * ( Structures::complex[.,.], int) -> ( Structures::complex[.,.])
 * ( Structures::complex, int) -> ( Structures::complex)
 *
 *****************************************************************************/

extern void boxes__escapeValue2(SACarg **ret1, SACarg *arg1, SACarg *arg2);

/*****************************************************************************
 * C declaration of function boxes::mandelbrot.
 *
 * defined instances:
 *
 * ( SNet::SNet, double[3]) -> ( SNet::SNet)
 *
 *****************************************************************************/

extern void boxes__mandelbrot2(SACarg **ret1, SACarg *arg1, SACarg *arg2);

/*****************************************************************************
 * C declaration of function boxes::intArrayToMonochrome.
 *
 * defined instances:
 *
 * ( int[.,.]) -> ( Color8::color[.,.])
 *
 *****************************************************************************/

extern void boxes__intArrayToMonochrome1(SACarg **ret1, SACarg *arg1);

/*****************************************************************************
 * C declaration of function boxes::normalizedIterationCount.
 *
 * defined instances:
 *
 * ( int[*], Structures::complex[*]) -> ( double[*])
 *
 *****************************************************************************/

extern void boxes__normalizedIterationCount2(SACarg **ret1, SACarg *arg1, SACarg *arg2);

/*****************************************************************************
 * C declaration of function boxes::displayImg.
 *
 * defined instances:
 *
 * ( SNet::SNet, Structures::color[800,800]) -> ( SNet::SNet)
 *
 *****************************************************************************/

extern void boxes__displayImg2(SACarg **ret1, SACarg *arg1, SACarg *arg2);

/*****************************************************************************
 * C declaration of function boxes::genComplexArray.
 *
 * defined instances:
 *
 * ( int[2], Structures::complex, Structures::complex) -> ( Structures::complex[.,.])
 *
 *****************************************************************************/

extern void boxes__genComplexArray3(SACarg **ret1, SACarg *arg1, SACarg *arg2, SACarg *arg3);

/*****************************************************************************
 * C declaration of function boxes::escapeTime.
 *
 * defined instances:
 *
 * ( Structures::complex, int) -> ( int)
 * ( Structures::complex[*], int) -> ( int[*])
 *
 *****************************************************************************/

extern void boxes__escapeTime2(SACarg **ret1, SACarg *arg1, SACarg *arg2);

