#!/bin/bash
#
# Print primes higher than $1 up to and include $2.
# The remaining arguments tell which program to execute.
#

if [ $# -lt 3 ] ||
  [[ $1 == *[!0-9]* ]]  ||
  [[ $2 == *[!0-9]* ]]
then
  echo "Usage: $0 number number program ..." >&2
  exit 1
fi

N=$1
M=$2
shift 2
[ $M -lt $N ] && let M=$N+10

"$@" <<EOI
<?xml version="1.0" ?>
<record xmlns="snet-home.org" type="data" mode="textual"  interface="C4SNet">
  <tag label="N">$N</tag>
  <tag label="M">$M</tag>
</record>
<record type="terminate" />
EOI
