#!/bin/sh

X=800
Y=600
N=1
M=1

[ $# -gt 0 ] && X=$1 && shift
[ $# -gt 0 ] && Y=$1 && shift
[ $# -gt 0 ] && N=$1 && shift
[ $# -gt 0 ] && M=$1 && shift

cat << EOI
<?xml version="1.0" ?>
<record xmlns="snet-home.org" type="data" mode="textual"  interface="C4SNet">
  <tag label="xdim">$X</tag>
  <tag label="ydim">$Y</tag>
  <tag label="nodes">$N</tag>
  <tag label="states">$M</tag>
</record>
<record type="terminate" />
EOI
