/**
 * @file example.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE example.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TAG_H_
#define _TAG_H_

#include "snetentities.h"

#define E__tag__NONE 0
#define F__tag__A 1
#define F__tag__B 2
#define T__tag__T 3

#define SNET__tag__NUMBER_OF_LABELS 4



#define SNET__tag__NUMBER_OF_INTERFACES 0


extern char *snet_tag_labels[];

extern char *snet_tag_interfaces[];


extern snet_tl_stream_t *SNet__tag___tag(snet_tl_stream_t *in_buf);

#endif

