/**
 * @file ts02.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE ts02.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TS02_H_
#define _TS02_H_

#include "snetentities.h"

#define E__ts02__NONE 0
#define F__ts02__a 1
#define F__ts02__b 2
#define F__ts02__c 3
#define F__ts02__d 4
#define F__ts02__e 5
#define F__ts02__f 6
#define T__ts02__T 7

#define SNET__ts02__NUMBER_OF_LABELS 8



#define SNET__ts02__NUMBER_OF_INTERFACES 0


extern const char *snet_ts02_labels[];

extern const char *snet_ts02_interfaces[];


extern snet_tl_stream_t *SNet__ts02___ts02(snet_tl_stream_t *in_buf);

#endif

