/**
 * @file ts01.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE ts01.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TS01_H_
#define _TS01_H_

#include "snetentities.h"

#define E__ts01__NONE 0
#define F__ts01__a 1
#define F__ts01__b 2
#define F__ts01__c 3
#define F__ts01__d 4
#define F__ts01__e 5
#define F__ts01__f 6
#define T__ts01__T 7

#define SNET__ts01__NUMBER_OF_LABELS 8



#define SNET__ts01__NUMBER_OF_INTERFACES 0


extern char *snet_ts01_labels[];

extern char *snet_ts01_interfaces[];


extern snet_tl_stream_t *SNet__ts01___ts01(snet_tl_stream_t *in_buf);

#endif

