#!/bin/bash --norc

if [[ $1 == *[!0-9]* ]] || [ $# -lt 2 ] || [ $1 -lt 0 ] || [ $1 -gt 30 ]; then
  echo "Usage: $0 number program ..." >&2
  exit 1
fi

NUM=$1
shift

"$@" <<EOI
<?xml version="1.0" ?>
<record xmlns="snet-home.org" type="data" mode="textual"  interface="C4SNet">
  <tag label="N">$NUM</tag>
</record>
<record type="terminate" />
EOI
