/**
 * @file ts00.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE ts00.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TS00_H_
#define _TS00_H_

#include "snetentities.h"

#define E__ts00__NONE 0
#define F__ts00__a 1
#define F__ts00__b 2
#define F__ts00__e 3
#define F__ts00__c 4
#define F__ts00__d 5
#define T__ts00__T 6

#define SNET__ts00__NUMBER_OF_LABELS 7



#define SNET__ts00__NUMBER_OF_INTERFACES 0


extern char *snet_ts00_labels[];

extern char *snet_ts00_interfaces[];


extern snet_tl_stream_t *SNet__ts00___ts00(snet_tl_stream_t *in_buf);

#endif

