/**
 * @file sudokusolve.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE sudokusolve.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _SUDOKUSOLVE_H_
#define _SUDOKUSOLVE_H_

#include "snetentities.h"

#define F__sudokusolve__board	1
#define F__sudokusolve__opts	2
#define T__sudokusolve__done	3

extern snet_buffer_t *SNet__sudokusolve___sudokusolve(snet_buffer_t *in_buf);

#endif

