# = = = = = = = = = = = = = = = = = = = =
TARGET    = mandelbrot_split_mpi
# = = = = = = = = = = = = = = = = = = = =

MPIMODE   = true
CMPIFLAG  = -DDISTRIBUTED_SNET
SMPIFLAG  = -distributed

include Makefile.tpl

