/**
 * @file main.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/



#include <buffer.h>
#include <record.h>
#include <parser.h>
#include <label.h>
#include <snetglobals.h>
#include <output.h>
#include <observers.h>

#include "mini.h"

snetin_label_t *globals_labels = NULL;
snetin_interface_t *globals_interfaces = NULL;

int main(int argc, char* argv[])
{

    int i = 0;
    snet_buffer_t *in_buf = SNetBufCreate(10);
    snet_buffer_t *out_buf = NULL;

    globals_labels = SNetInLabelInit(snet_mini_labels, SNET__mini__NUMBER_OF_LABELS);
    globals_interfaces = SNetInInterfaceInit(snet_mini_interfaces, SNET__mini__NUMBER_OF_INTERFACES);

    SNetGlobalInitialise();
    SNetInitObserverSystem();

    out_buf = SNet__mini___mini(in_buf);

    if(SNetInOutputInit(out_buf) != 0){
        return 1;
    }

    SNetInParserInit(in_buf);

    i = PARSE_CONTINUE;
    while(i != PARSE_TERMINATE){
        i = SNetInParserParse();
    }

    if(SNetInOutputDestroy() != 0){
        return 1;
    }

    if(in_buf != NULL){
        SNetBufDestroy(in_buf);
    }

    SNetInParserDestroy();

    SNetDestroyObserverSystem();

    SNetInLabelDestroy(globals_labels);
    SNetInInterfaceDestroy(globals_interfaces);

    return 0;
}
