/**
 * @file mini.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "mini.h"
#include "networkinterface.h"
#include "SAC2SNet.h"
#include "A.h"

char *snet_mini_labels[] = {
	"E__mini__None",
	"A",
	"B"};

char *snet_mini_interfaces[] = {
	"SAC2SNet"};

static void SNet__mini__A(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_A = NULL;

  rec = SNetHndGetRecord(hnd);

  field_A = SNetRecTakeField(rec, F__mini__A);

  A(hnd, field_A);
}

snet_buffer_t *SNet__mini___mini(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;

  out_type = SNetTencTypeEncode(1, 
              SNetTencVariantEncode(
                SNetTencCreateVector(1, F__mini__B), 
                SNetTencCreateVector(0), 
                SNetTencCreateVector(0)));

  out_buf = SNetBox(in_buf, 
              &SNet__mini__A, 
              out_type);

  return (out_buf);
}

int main_mini(int argc, char* argv[])
{
  SNetGlobalInitialise();
  SAC2SNet_init(I__mini__SAC2SNet);
  
  return SNetInRun(snet_mini_labels, SNET__mini__NUMBER_OF_LABELS,
              snet_mini_interfaces, SNET__mini__NUMBER_OF_INTERFACES,
              SNet__mini___mini);
}

