/**
 * @file mini.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _MINI_H_
#define _MINI_H_

#include "snetentities.h"

#define E__mini__NONE 0
#define F__mini__A 1
#define F__mini__B 2

#define SNET__mini__NUMBER_OF_LABELS 3


#define I__mini__SAC2SNet 0

#define SNET__mini__NUMBER_OF_INTERFACES 1


extern char *snet_mini_labels[];

extern char *snet_mini_interfaces[];


extern snet_buffer_t *SNet__mini___mini(snet_buffer_t *in_buf);

#endif

