/**
 * @file mini.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "mini.h"
#include "A.h"

static void SNet__mini__A(snet_handle_t *hnd) {
  snet_record_t *rec = NULL;
  void *field_A = NULL;

  rec = SNetHndGetRecord(hnd);

  field_A = SNetRecTakeField(rec, F__mini__A);

  A(hnd, field_A);
}

static snet_buffer_t *SNet__mini(snet_buffer_t *in_buf) {
  snet_buffer_t *out_buf = NULL;
  snet_typeencoding_t *out_type = NULL;

  out_type = SNetTencTypeEncode(1, 
              SNetTencVariantEncode(
                SNetTencCreateVector(1, F__mini__B), 
                SNetTencCreateVector(0), 
                SNetTencCreateVector(0)));

  out_buf = SNetBox(in_buf, 
              &SNet__mini__A, 
              out_type);

  return (out_buf);
}

