/**
 * @file mini.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _MINI_H_
#define _MINI_H_

#include "snetentities.h"

#define F__mini__A	1
#define F__mini__B	2
#define E__mini__OFFSET	3

extern snet_buffer_t *SNet__mini___mini(snet_buffer_t *in_buf);

#endif

