#!/bin/sh

#------------------------------------------------------------------------------
# Shows the help text

show_usage()
{
    echo "USAGE: clean-build-dir [options] DIR_FILE"
    echo
    echo "where DIR_FILE a file that contains entries of the"
    echo "directories to be cleaned."
    echo
    echo "and options include:"
    echo "    -d      Delete directories."
    echo "    -comment <'character'>"
    echo "            Specifies that lines starting with <character>"
    echo "            should be treated as comments and not displayed."
    echo "    --help  Display available options."
    echo   

    exit $1
}

#------------------------------------------------------------------------------
# Initialize some variables

dirs=""
dir_file=""
delete_dirs=0
comment_chr=""
current_dir=$PWD
cat_xargs_cmd=`echo $0 | sed -n -e "s/clean-build-dir/cat-xargs/p"`

#------------------------------------------------------------------------------
#Parse command line and setup option

while [ $# -gt 0 ]
do
    case "$1" in
    -d)
        delete_dirs=1
        ;;
    -comment)
        shift
        comment_chr=$1
        ;;
    --help)
        show_usage 0
        ;;
    *)
        if [ "$dir_file" == "" ]
        then
            dir_file=$1
        else
            echo "Error: Invalid argument '$1'."
            echo
            
            show_usage 1
        fi
        ;;
    esac
    shift
done

#------------------------------------------------------------------------------
# Main

if [ "$dir_file" == "" ]
then
   echo "Error: No direcory file has been specified."
   echo
   show_usage 1
fi


if [ "$comment_ch" == "" ]
then
    dirs=`$cat_xargs_cmd $dir_file`
else
    dirs=`$cat_xargs_cmd $dir_file -comment $comment_chr`
fi

for d in $dirs
do
    if [ $delete_dirs -eq 1 ]
    then
        rm -rf $d
    else
        rm -rf $d/*
    fi
done

#----------------------------------------------------------------------------p-
#------------------------------------------------------------------------------

