#!/bin/sh

#------------------------------------------------------------------------------
# Initialize some variables

del_links=0

target_dir=""
settings_file=""

#------------------------------------------------------------------------------
# Shows the help text

show_usage()
{
    echo "USAGE: make-links [option] 'settings_file'"
    echo
    echo "where 'settings_file' is:"
    echo "     file containing the links to be made"
    echo
    echo "and option is:"
    echo "     -del     Delete links"
    echo "     -d 'dir' Prefix paths in settings file with 'dir'"
    echo "     --help   Print available options"
    echo

    exit $1
}

missing_target_error()
{
    echo
    echo "!!! ERROR !!!"
    echo "Target file / directory $1 does not exist."
    echo

    exit 1
}

invalid_lnk_type_error()
{
    echo
    echo "!!! ERROR !!!"
    echo "Specified type of link is invalid."
    echo

    exit 1
}

stop_due_to_errors()
{
    echo
    echo "!!! ERROR !!!"
    echo "Script has stopped due to unexpected errors."
    echo

    exit 1
}

#------------------------------------------------------------------------------

create_link()
{
    target=""
    cp_cmd_args=""
    ln_cmd_args="-s"

    if [ "$target_dir" != "" ]
    then
        target="$target_dir/$3"
    else
        target=$3
    fi

    lnk=`eval echo "$2"`
    target=`eval echo "$target"`

    if [ -d $target ]
    then
        cp_cmd_args="-r"
    else
        if [ -f $target ]
        then
            cp_cmd_args=""
        else
            missing_target_error $target
        fi
    fi

    if [ -e $lnk ]
    then
        return
    fi    
    
    echo "Creating link $lnk..."
    
    case $1 in
    s)
        ln $ln_cmd_args $target $lnk
        ;;
    fc)
        cp $cp_cmd_args $target $lnk
        ;;
    dc)
        cp $cp_cmd_args $target $lnk
        ;;
    *)
        invalid_lnk_type_error
        ;;
    esac

    if [ $? -ne 0 ]
    then
        stop_due_to_errors
    fi
}

delete_link()
{
    lnk=`eval echo "$2"`

    if [ ! -e $lnk ]
    then
        return
    fi    
    
    echo "Deleting link $lnk..."
    
    case $1 in
    s)
        rm -f $lnk
        ;;
    fc)
        rm -f $lnk
        ;;
    dc)
        rm -rf $lnk
        ;;
    *)
        invalid_lnk_type_error
        ;;
    esac

    if [ $? -ne 0 ]
    then
        stop_due_to_errors
    fi
}

#------------------------------------------------------------------------------
# Main

# echo "Links Creator ver 1.0.0"

#------------------------------------------------------------------------------
#Parse command line and setup option

while [ $# -gt 0 ]
do
    case "$1" in
    -del)
        del_links=1
        ;;
    -d)
        shift
        target_dir=$1
        ;;
    --help)
        show_usage 0
        ;;
    *)
        if [ "$settings_file" == "" ]
        then
            settings_file=$1
        else
            echo "Error: Invalid argument '$1'."
            echo
            
            show_usage 1
        fi
        ;;
    esac
    shift
done

#---

if [ "$settings_file" == "" ] || [ ! -f "$settings_file" ]
then
    echo
    echo "!!! ERROR !!!"
    echo "Missing settings file or file does not exist."
    echo

    exit 1
fi

#------------------------------------------------------------------------------
# Read and parse settings file

while read -r line 
do
    line=`echo $line | sed -e "s/\n//g"`

    if [ "$line" == "" ]
    then
        continue
    fi

    fields=`echo $line | awk -F= '{ printf("%s\n%s\n%s", $1, $2, $3) }'`
    field_cnt=0;

    for field in $fields
    do
        case $field_cnt in
        0)
            lnk_type=$field
            ;;
        1)
            lnk=$field
            ;;
        2)
            lnk_target=$field
            ;;
        esac

        field_cnt=$(( $field_cnt + 1 ))
    done

    if [ $del_links -eq 0 ]
    then
        create_link $lnk_type $lnk $lnk_target
    else
        delete_link $lnk_type $lnk $lnk_target
    fi
done < "$settings_file"

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

