#!/bin/sh

if [ $# != 2 ] || [ ! -x $1 ] || [ $2 -lt 0 ] || [ $2 -gt 30 ]; then
  echo "Usage: $0 executable number" >&2
  exit 1
fi

EXE=$1
NUM=$2
shift 2

cat >input <<EOI
<?xml version="1.0" ?>
<record xmlns="snet-home.org" type="data" mode="textual"  interface="C4SNet">
  <tag label="N">$NUM</tag>
</record>
<record type="terminate" />
EOI
$EXE -i input "$@"
