#!/usr/bin/env bash

# runTests takes a base dir followed by an (optional) list of tests from that
# subdirectory to run. If no such list is given all tests are run.
function runTests {
  local base tests

  base=$1; shift

  if [ $# -gt 0 ]; then
    tests=$@
  else
    tests=($base/*/)
    tests=(${tests[@]%/})
    tests=(${tests[@]#$base/})
  fi

  # For all tests
  for dir in "${tests[@]}"; do
    fail_flag=false
    # Try to compile test
    if make -C $base/$dir 2>/dev/null >/dev/null; then
      # If the compile succeeded, run the test for each XML file.
      for input in $base/$dir/*.xml; do
        if [ -f $base/$dir/$dir ]; then
          if run $base/$dir/$dir $input out.bak -m A; then
            # If the test exited succesfully, verify the output
            if ! ./compare ${input%.xml} out.bak; then
              echo "Results differ for $dir with ${input#$base/$dir/}"
              mv out.bak $dir-${input#$base/$dir\/}.out
            else
              echo "OK: $dir with ${input#$base/$dir/}"
              rm -f out.bak
            fi
          else
            echo "Execution failed for $dir with ${input#$base/$dir/}"
            rm -f out.bak
            fail_flag=true
          fi
        fi
      done
    else
      echo "Compile failed for $dir"
    fi
    if ! $fail_flag; then
      make -C $base/$dir clean 2>/dev/null >/dev/null
    fi
  done
}

if [ $# -gt 0 ]; then
  categories=$1; shift
else
  categories=(*/)
  categories=(${categories[@]%/})
fi

for category in ${categories[@]}; do
  for config in $category/*.config; do
    # Set default config values
    function run {
      $1 -i $2 -o $3
    }
    export SNETTESTFLAGS=""
    export RUN=1

    # If a config file exists, source it to set the above values
    if [ -f $config ]; then
      source $config
      config=${config#$category/}
      config=${config%.config}
    else
      config=""
      if [ -f $category/config ]; then
        source $category/config
      fi
    fi

    if [ $RUN -ne 0 ]; then
      if [ -n "$config" ]; then
        echo "Running $category $config tests:"
      else
        echo "Running $category tests:"
      fi

      runTests $category $@
      echo
    fi
  done
done
