#!/bin/sh

#------------------------------------------------------------------------------
# Shows the help text

show_usage()
{
    echo "USAGE: exec-silent [options] COMMAND [args]"
    echo
    echo "where COMMAND the command to execute and [arg] its arguments"
    echo
    echo "and options include:"
    echo "       --help    Display available options."
    echo   

    exit $1
}

#------------------------------------------------------------------------------
# Initialize some variables

cmd=""
args=""

#------------------------------------------------------------------------------
#Parse command line and setup option

if [ $# -eq 0 ]
then
    show_usage 1
fi

while [ $# -gt 0 ]
do
    case "$1" in
    --help)
        show_usage 0
        ;;
    *)
        if [ "$cmd" == "" ]
        then
            cmd="$1"
        else
            args="$args $1"
        fi

        ;;
    esac
    shift
done

#------------------------------------------------------------------------------
# Main

cmd_output=`$cmd $args 2>&1`
cmd_exit_code=$?

if [ $cmd_exit_code -ne 0 ]
then
    echo "$cmd_output"
fi

exit $cmd_exit_code

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

