/**
 * @file test01.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE test01.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _TEST01_H_
#define _TEST01_H_

#include "snetentities.h"

#define E__test01__NONE 0
#define F__test01__a 1
#define F__test01__b 2
#define F__test01__c 3
#define F__test01__d 4
#define F__test01__e 5
#define F__test01__f 6
#define T__test01__T 7
#define T__test01__I 8

#define SNET__test01__NUMBER_OF_LABELS 9



#define SNET__test01__NUMBER_OF_INTERFACES 0


extern const char *snet_test01_labels[];

extern const char *snet_test01_interfaces[];


extern snet_tl_stream_t *SNet__test01___test01(snet_tl_stream_t *in_buf);

#endif

