/**
 * @file mini.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE mini.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "mini.h"
#include "networkinterface.h"
#include "SAC4SNet.h"
#include "distribution.h"
#include "list.h"

char *snet_mini_labels[] = {
	"E__mini__None",
	"A"};

char *snet_mini_interfaces[] = {
	"SAC4SNet"};

extern void mini__A2( SACarg **hnd_return, SACarg *hnd, SACarg *arg_0);

static void *SNetCall__boxA( void *handle, SACarg *arg_0)
{
  SACarg *hnd_return, *hnd;

  hnd = SACARGconvertFromVoidPointer( SACTYPE_SNet_SNet, handle);
  mini__A2( &hnd_return, hnd, arg_0);

  return( SACARGconvertToVoidPointer( SACTYPE_SNet_SNet, hnd_return));
}


static void SNet__mini__boxA(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  void *field_A = NULL;

  rec = SNetHndGetRecord(hnd);

  field_A = SNetRecTakeField(rec, F__mini__A);

  SNetCall__boxA(hnd, field_A);
}

extern void mini__B1( SACarg **hnd_return, SACarg *hnd);

static void *SNetCall__B( void *handle)
{
  SACarg *hnd_return, *hnd;

  hnd = SACARGconvertFromVoidPointer( SACTYPE_SNet_SNet, handle);
  mini__B1( &hnd_return, hnd);

  return( SACARGconvertToVoidPointer( SACTYPE_SNet_SNet, hnd_return));
}


static void SNet__mini__B(snet_handle_t *hnd)
{
  struct record *rec = NULL;

  rec = SNetHndGetRecord(hnd);

  SNetCall__B(hnd);
}

static snet_stream_t *SNet__mini___SL___P1(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "B", 
              &SNet__mini__B, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(1, F__mini__A), 
                  SNetIntListCreate(0), 
                  SNetIntListCreate(0))));

  return (out_buf);
}

static snet_stream_t *SNet__mini___SL___P2(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetFilter(in_buf, info, location, 
              SNetVariantCreateEmpty(), 
              SNetExprListCreate(1, 
                SNetEconstb( true)), 
              SNetFilterInstrListListCreate(1, 
                SNetFilterInstrListCreate(1, 
                  SNetCreateFilterInstruction(create_record))));

  return (out_buf);
}

static snet_stream_t *SNet__mini___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetParallel(in_buf, info, location, 
              SNetVariantListListCreate(2, 
                SNetVariantListCreate(0), 
                SNetVariantListCreate(1, 
                  SNetVariantCreate(
                    SNetIntListCreate(0), 
                    SNetIntListCreate(0), 
                    SNetIntListCreate(0)))), 
              &SNet__mini___SL___P1, 
              &SNet__mini___SL___P2);

  return (out_buf);
}

static snet_stream_t *SNet__mini___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "boxA", 
              &SNet__mini__boxA, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(1, F__mini__A), 
                  SNetIntListCreate(0), 
                  SNetIntListCreate(0))));

  return (out_buf);
}

snet_stream_t *SNet__mini___mini(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__mini___SL, 
              &SNet__mini___SR);

  return (out_buf);
}

int SNetMain__mini(int argc, char* argv[])
{
  int ret = 0;

  SAC4SNetInit(I__mini__SAC4SNet);
  
  ret = SNetInRun(argc, argv,
              snet_mini_labels,
              SNET__mini__NUMBER_OF_LABELS,
              snet_mini_interfaces,
              SNET__mini__NUMBER_OF_INTERFACES,
              SNet__mini___mini);

  SNetInterfacesDestroy();

  return( ret);
}

