/*----------------------------------------------------------------------------*/
/*
      -------------------------------------------------------------------

              * * * * ! SVP S-Net Graph Walker Runtime ! * * * *

                  Computer Systems Architecture (CSA) Group
                            Informatics Institute
                        University Of Amsterdam  2008
                         
      -------------------------------------------------------------------

    File Name      : networkinterface.h

    File Type      : Header File

    ---------------------------------------

    File 
    Description    : Header included from the S-Net compiler 
                     generated code.

    Updates 
    Description    : N/A

*/
/*----------------------------------------------------------------------------*/

#ifndef __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H
#define __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H

#ifndef __SVPSNETGWRT_SNETC_SNETENTITIES_H
#error \
The header file 'snetentities.h' has not been \
included (it must be included before 'networkinterface.h')
#endif

/**
 * Function used in the "main" generated by the compiler 
 * to start the network interface component.
 */

static inline int 
SNetInRun(
    int    argc,
    char **argv,
    char **lblv,
    int    lblc,
    char **bliv, 
    int    blic, 
    snet_graphctor_fptr_t gctor_fun)
{
    return SNetNetIfRun(argc, argv, lblc, lblv, blic, bliv, gctor_fun);
}

/*----------------------------------------------------------------------------*/
/* Function used to register box language interfaces */

static inline bool
SNetGlobalRegisterInterface(
    snet_bli_id_t        id,
    snet_bli_freefptr_t  freefun,
    snet_bli_copyfptr_t  copyfun,
    snet_bli_serfptr_t   serfun,
    snet_bli_deserfptr_t deserfun)
{
    return SNetGlobalBliRegister(id, freefun, copyfun, serfun, deserfun);
}

#endif // __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H

/*------------------------------- END OF FILE --------------------------------*/
/*----------------------------------------------------------------------------*/

