/*----------------------------------------------------------------------------*/
/*
      -------------------------------------------------------------------

              * * * * ! SVP S-Net Graph Walker Runtime ! * * * *

                  Computer Systems Architecture (CSA) Group
                            Informatics Institute
                        University Of Amsterdam  2008
                         
      -------------------------------------------------------------------

    File Name      : networkinterface.h

    File Type      : Header File

    ---------------------------------------

    File 
    Description    : Header included from the S-Net compiler 
                     generated code.

    Updates 
    Description    : N/A

*/
/*----------------------------------------------------------------------------*/

#ifndef __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H
#define __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H

extern int 
SNetIfRun(
    int    argc,
    char **argv,
    int    lblc,
    char **lblv,
    int    blic, 
    char **bliv,
    snet_graphctor_fptr_t gctor_fun);

/*----------------------------------------------------------------------------*/
/**
 * Function used in the "main" generated by
 * the compiler.
 */
static inline int 
SNetInRun(
    int    argc,
    char **argv,
    char **lblv,
    int    lblc,
    char **bliv, 
    int    blic, 
    snet_graphctor_fptr_t gctor_fun)
{
    return SNetIfRun(argc, argv, lblc, lblv, blic, bliv, gctor_fun);
}

#endif // __SVPSNETGWRT_SNETC_NETWORKINTERFACE_H

/*------------------------------- END OF FILE --------------------------------*/
/*----------------------------------------------------------------------------*/

